app:
  active-profile: ServletAppProfile

profiles:
  - name: ServletAppProfile
    model: include
    matching: satisfy-any
    tags:
      - ServletApp

#web:
#  servlet:
#    url-mappings:
#      - /api/v1
#      - /api/v2
#  dispatch:
